import { translated } from './names.js';
import { organName } from './organ-names.js';
const names={
 'Angle of mouth':'Ângulo da boca','Anterior notch of auricle':'Incisura anterior da orelha','Antihelix':'Anti-hélice','Antitragus':'Antítrago','Apex of auricle':'Ápice da orelha','Auricular region':'Região auricular','Auricular tubercle':'Tubérculo auricular','Buccal region':'Região da bochecha','Cavity of concha':'Cavidade da concha da orelha','Concha of auricle':'Concha da orelha','Crura of antihelix':'Ramos da anti-hélice','Cymba conchae':'Cimba da concha','Eminentia conchae':'Eminência da concha','Eminentia fossae triangularis':'Eminência da fossa triangular','Eminentia scaphae':'Eminência da escafa','Eyelashes':'Cílios','Fossa antihelica':'Fossa da anti-hélice','Frontal region':'Região frontal','Hairs of eyebrow':'Sobrancelha','Hairs of head':'Cabelos','Helix':'Hélice','Infra-orbital region':'Região infraorbital','Intertragic incisure':'Incisura intertrágica','Labial commissure':'Comissura labial','Lobule of auricle':'Lóbulo da orelha','Mastoid region':'Região mastóidea','Mental region':'Região do queixo','Mentolabial sulcus':'Sulco mentolabial','Nasal region':'Região nasal','Nasolabial sulcus':'Sulco nasolabial','Occipital region':'Região occipital','Oral region':'Região oral','Orbital region':'Região orbital','Parietal region':'Região parietal','Parotideomasseteric region':'Região parotídeo-massetérica','Posterior auricular groove':'Sulco auricular posterior','Scapha':'Escafa da orelha','Temporal region':'Região temporal','Tragus':'Trago','Triangular fossa':'Fossa triangular','Zygomatic region':'Região zigomática',

 'Ethmoid bone':'Etmoide','Frontal bone':'Osso frontal','Incus':'Bigorna','Inferior nasal concha bone':'Concha nasal inferior','Lacrimal bone':'Osso lacrimal','Malleus':'Martelo','Mandible':'Mandíbula','Maxilla':'Maxila','Nasal bone':'Osso nasal','Occipital bone':'Osso occipital','Palatine bone':'Osso palatino','Parietal bone':'Osso parietal','Sphenoid bone':'Esfenoide','Stapes':'Estribo','Temporal bone':'Osso temporal','Vomer':'Vômer','Zygomatic bone':'Osso zigomático',
 'Common tendinous ring':'Anel tendíneo comum','Deep part of masseter':'Masseter — parte profunda','Epicranial aponeurosis':'Aponeurose epicraniana','Frontalis muscle':'Músculo frontal','Inferior head of lateral pterygoid muscle':'Pterigóideo lateral — cabeça inferior','Inferior oblique muscle':'Oblíquo inferior do olho','Inferior rectus muscle':'Reto inferior do olho','Inferior tarsus':'Tarso inferior','Lateral rectus muscle':'Reto lateral do olho','Levator palpebrae superioris':'Levantador da pálpebra superior','Medial pterygoid muscle':'Pterigóideo medial','Medial rectus muscle':'Reto medial do olho','Occipitalis muscle':'Músculo occipital','Superficial part of masseter':'Masseter — parte superficial','Superior head of lateral pterygoid muscle':'Pterigóideo lateral — cabeça superior','Superior oblique muscle':'Oblíquo superior do olho','Superior rectus muscle':'Reto superior do olho','Superior tarsus':'Tarso superior','Temporalis muscle':'Músculo temporal','Temporoparietalis muscle':'Músculo temporoparietal','Trochlea of superior oblique muscle':'Tróclea do oblíquo superior',
 'Cochlea':'Cóclea','Cornea':'Córnea','Iris':'Íris','Lacrimal gland':'Glândula lacrimal','Lens':'Cristalino','Retina':'Retina','Sclera':'Esclera','Tympanic membrane':'Membrana timpânica','Vestibule':'Vestíbulo da orelha interna','Parotid gland':'Glândula parótida','Sublingual gland':'Glândula sublingual','Submandibular gland':'Glândula submandibular','Tongue':'Língua'
};
export function headLabel(data){
 if(data.organLabel)return data.organLabel;
 const source=data.sourceName,base=source.replace(/\.[lr]$/,'');if(names[base])return names[base];
 const m=base.match(/^(Upper|Lower) (.*)$/);if(m){const teeth={'canine':'Canino','first molar tooth':'Primeiro molar','second molar tooth':'Segundo molar','first premolar':'Primeiro pré-molar','second premolar':'Segundo pré-molar','lateral incisor':'Incisivo lateral','medial incisor':'Incisivo central'};if(teeth[m[2]])return `${teeth[m[2]]} ${m[1]==='Upper'?'superior':'inferior'}`;}
 return organName(source)||translated(source);
}
export function sideLabel(source){return source.endsWith('.l')?'Lado esquerdo':source.endsWith('.r')?'Lado direito':'';}
