import './head.css';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';
import { toothInfo,permanentTeeth } from './teeth.js';
import { headLabel,sideLabel } from './head-names.js';
const $=id=>document.getElementById(id);
const configs={face:{title:'Rosto adulto',files:['face','senses','bones'],coverage:'Superfície externa da cabeça adulta, com olhos e dentes. Modelo anatômico sem textura fotográfica.'},bones:{title:'Ossos da cabeça',files:['bones'],coverage:'Dentição permanente: 28 dentes em 3D. Os quatro sisos estão no índice, sem modelo nesta coleção.'},muscles:{title:'Músculos da cabeça',files:['muscles'],coverage:'Músculos da face, mastigação e olhos, com algumas estruturas associadas.'},organs:{title:'Órgãos da cabeça',files:['brain','senses','viscera'],coverage:'Cérebro, cerebelo, tronco encefálico, estruturas dos olhos e ouvidos, língua e glândulas. Coleção parcial.'}};
let renderer,scene,camera,controls,activeModel=null,modelId='face',groups=[],selected=null,version=0,queued=false,wholeBox;
const cache=new Map(),history=[];
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function draw(){if(queued||!renderer)return;queued=true;requestAnimationFrame(()=>{queued=false;controls.update();renderer.render(scene,camera);updateToothMarker();});}
function boundsOf(items){const box=new THREE.Box3();for(const g of items)for(const mesh of g.meshes)box.expandByObject(mesh);return box;}
function frame(box,direction){if(!box||box.isEmpty())return;const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());const v=THREE.MathUtils.degToRad(camera.fov),h=2*Math.atan(Math.tan(v/2)*camera.aspect);const distance=Math.max(size.y/(2*Math.tan(v/2)),size.x/(2*Math.tan(h/2)),size.z/2)*1.32;const dir=direction||camera.position.clone().sub(controls.target).normalize();camera.position.copy(center).addScaledVector(dir,Math.max(distance,.03));controls.target.copy(center);controls.update();draw();}
function resize(){const el=$('head-canvas');if(!el.clientWidth||!el.clientHeight)return;renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();if(wholeBox)frame(wholeBox);draw();}
function renderList(){const q=normalize($('search').value);const visible=groups.filter(g=>normalize(g.label+' '+g.side+' '+(g.tooth?.number||'')+' '+g.sources.join(' ')).includes(q));$('count').textContent=String(visible.length);$('structure-list').replaceChildren(...visible.map(g=>{const b=document.createElement('button');b.textContent=g.tooth?`${g.tooth.number} · ${g.tooth.name}`:g.label;b.dataset.structure=g.id;b.classList.toggle('active',g===selected);b.classList.toggle('hidden-structure',!g.meshes.some(m=>m.visible));b.setAttribute('aria-pressed',String(g===selected));const sub=document.createElement('small');sub.textContent=(g.side||'Estrutura anatômica')+(g.meshes.some(m=>m.visible)?'':' · Oculta');b.append(sub);b.onclick=()=>select(g);return b;}));if(!visible.length){const p=document.createElement('p');p.textContent='Nenhuma estrutura encontrada neste modelo.';$('structure-list').append(p);}}
function select(group){if(selected)selected.meshes.forEach(m=>m.material.emissive.set(0));selected=group;if(group){group.meshes.forEach(m=>m.material.emissive.set(0x17695b));$('selected-name').textContent=group.tooth?`${group.tooth.number} · ${group.tooth.name}`:group.label;$('selected-side').textContent=group.tooth?'FDI · Dente permanente · '+group.tooth.arch:(group.side||'Estrutura anatômica');}else{$('selected-name').textContent='Toque no modelo';$('selected-side').textContent='Escolha uma parte para ver seu nome.';}$('isolate').disabled=$('hide').disabled=!group;$('hide').textContent=group&&!group.meshes.some(m=>m.visible)?'Mostrar':'Ocultar';syncDentalState();renderList();draw();}
function snapshot(){history.push(groups.map(g=>g.meshes.map(m=>m.visible)));if(history.length>30)history.shift();$('undo').disabled=false;}
function restore(){if(groups.some(g=>g.meshes.some(m=>!m.visible)))snapshot();groups.forEach(g=>g.meshes.forEach(m=>m.visible=true));$('search').value='';select(null);frame(wholeBox,new THREE.Vector3(0,0,1));$('orientation').textContent='Vista de frente';}
function color(source,id){if(id==='face'){if(/Hairs|Eyelashes/.test(source))return 0x44362e;if(/incisor|canine|premolar|molar/.test(source))return 0xe8dfc8;if(/Sclera/.test(source))return 0xdddcd1;if(/Iris/.test(source))return 0x556a4a;if(/Cornea|Lens/.test(source))return 0xb6cfc7;if(/Angle of mouth|Labial commissure/.test(source))return 0x945f58;return 0xb78970;}if(id==='bones')return /incisor|canine|premolar|molar/.test(source)?0xebe4ce:0xd6c5a7;if(id==='muscles')return /aponeurosis|tendinous|tarsus|Trochlea/i.test(source)?0xd0bdaa:0xb75445;if(/Sclera/.test(source))return 0xe4e8dc;if(/Iris/.test(source))return 0x54796c;if(/Cornea|Lens/.test(source))return 0xb3d4ce;if(/Retina/.test(source))return 0xb85e50;if(/Cochlea|Vestibule|Tympanic/.test(source))return 0xddb785;if(/Tongue/.test(source))return 0xbb6266;return 0xce9589;}
const draco=new DRACOLoader();draco.setDecoderPath('/draco/');draco.setWorkerLimit(2);const loader=new GLTFLoader().setDRACOLoader(draco);
async function loadModel(id){const config=configs[id];const loaded=await Promise.all(config.files.map(f=>loader.loadAsync(`/head/${f}.glb`)));const group=new THREE.Group();const byName=new Map();
 for(const gltf of loaded){gltf.scene.traverse(m=>{if(!m.isMesh)return;const data=m.userData,source=data.sourceName;if(id==='face'&&!/region|auricle|Antihelix|Antitragus|Auricular|concha|antihelix|Eminentia|Eyelashes|Fossa antihelica|Hairs|Helix|Intertragic|Labial|Mentolabial|Nasolabial|Scapha|Tragus|Triangular|Angle of mouth|Sclera|Cornea|Iris|Lens/.test(source)&&!toothInfo(source)){m.visible=false;return;}const label=headLabel(data),side=sideLabel(source),key=label+'|'+side;m.material=new THREE.MeshStandardMaterial({color:color(source,id),roughness:.62});if(/Cornea/.test(source)){m.material.transparent=true;m.material.opacity=.28;m.material.depthWrite=false;}if(!byName.has(key))byName.set(key,{id:key,label,side,tooth:toothInfo(source),sources:[],meshes:[]});const record=byName.get(key);record.sources.push(source);record.meshes.push(m);m.userData.record=record;});group.add(gltf.scene);}
 return {group,groups:[...byName.values()].sort((a,b)=>a.label.localeCompare(b.label,'pt-BR')||a.side.localeCompare(b.side,'pt-BR'))};}
async function choose(id){const request=++version;modelId=id;delete document.body.dataset.ready;$('loading').hidden=false;$('loading').replaceChildren();const spinner=document.createElement('span');spinner.className='spinner';const message=document.createElement('strong');message.textContent=`Carregando ${configs[id].title.toLowerCase()}…`;$('loading').append(spinner,message);for(const button of document.querySelectorAll('[data-model]')){button.classList.toggle('active',button.dataset.model===id);button.setAttribute('aria-pressed',String(button.dataset.model===id));}$('model-title').textContent=configs[id].title;$('coverage').textContent=configs[id].coverage;$('dental-tools').hidden=id!=='bones';
 try{if(!cache.has(id))cache.set(id,loadModel(id).catch(error=>{cache.delete(id);throw error;}));const data=await cache.get(id);if(request!==version)return;if(activeModel)scene.remove(activeModel);select(null);activeModel=data.group;groups=data.groups;scene.add(activeModel);history.length=0;$('undo').disabled=true;wholeBox=boundsOf(groups);restore();$('undo').disabled=true;history.length=0;$('loading').hidden=true;document.body.dataset.ready=id;draw();}
 catch(error){if(request!==version)return;console.error(error);$('loading').replaceChildren();const p=document.createElement('strong');p.textContent='Não foi possível carregar este modelo.';const hint=document.createElement('span');hint.textContent='Confira a conexão e tente novamente.';const retry=document.createElement('button');retry.textContent='Tentar novamente';retry.onclick=()=>choose(id);$('loading').append(p,hint,retry);}}
function updateToothMarker(){
 const marker=$('selected-tooth-marker');if(!selected?.tooth||!selected.meshes.some(m=>m.visible)){marker.hidden=true;return;}
 const center=boundsOf([selected]).getCenter(new THREE.Vector3()).project(camera);const canvas=$('head-canvas');
 marker.hidden=center.z>1||center.z< -1||Math.abs(center.x)>1||Math.abs(center.y)>1;
 marker.textContent=String(selected.tooth.number);marker.style.left=`${(center.x+1)/2*canvas.clientWidth+10}px`;marker.style.top=`${(-center.y+1)/2*canvas.clientHeight-24}px`;
}
function syncDentalState(){
 $('teeth-only').checked=modelId==='bones'&&groups.filter(g=>!g.tooth).every(g=>g.meshes.every(m=>!m.visible));
 for(const button of document.querySelectorAll('[data-tooth]')){const active=Number(button.dataset.tooth)===selected?.tooth?.number;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));}
}
function teethOnly(enabled){snapshot();groups.forEach(g=>g.meshes.forEach(m=>m.visible=!enabled||!!g.tooth));select(null);frame(enabled?boundsOf(groups.filter(g=>g.tooth)):wholeBox,new THREE.Vector3(0,0,1));$('orientation').textContent='Vista de frente';}
async function selectTooth(tooth){
 if(document.body.dataset.ready!=='bones')await choose('bones');if(document.body.dataset.ready!=='bones')return;
 const group=groups.find(g=>g.tooth?.number===tooth.number);
 if(!group){select(null);$('selected-name').textContent=`${tooth.number} · ${tooth.name}`;$('selected-side').textContent='FDI · Sem modelo 3D nesta coleção';$('dental-feedback').textContent=`${tooth.number} — ${tooth.name}: nome disponível, mas sem geometria 3D nesta coleção.`;return;}
 teethOnly(true);select(group);$('dental-feedback').textContent=`Selecionado: ${tooth.number} — ${tooth.name}.`;
 document.querySelector('.stage').scrollIntoView({block:'start',behavior:'smooth'});
}
function setupDentalChart(){
 for(const quadrant of [1,2,4,3]){const section=document.createElement('section');const heading=document.createElement('h3');heading.textContent={1:'Superior direito',2:'Superior esquerdo',3:'Inferior esquerdo',4:'Inferior direito'}[quadrant];section.append(heading);
 for(const tooth of permanentTeeth.filter(t=>t.quadrant===quadrant)){const button=document.createElement('button');button.dataset.tooth=String(tooth.number);button.setAttribute('aria-pressed','false');const number=document.createElement('b');number.textContent=String(tooth.number);const name=document.createElement('span');name.textContent=tooth.name;if(tooth.position===8){button.classList.add('missing-tooth');const small=document.createElement('small');small.textContent='Sem modelo 3D';name.append(small);}button.append(number,name);button.onclick=()=>selectTooth(tooth);section.append(button);}$('quadrants').append(section);}
 $('teeth-only').onchange=e=>teethOnly(e.target.checked);
 $('open-dental-chart').onclick=()=>{$('dental-chart').open=true;$('dental-chart').scrollIntoView({block:'start',behavior:'smooth'});};
}
function init(){scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(35,1,.0005,20);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;$('head-canvas').append(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.12;controls.minDistance=.025;controls.maxDistance=3;controls.addEventListener('change',draw);
 scene.add(new THREE.HemisphereLight(0xffffff,0x657a73,2.3));const key=new THREE.DirectionalLight(0xffead9,3);key.position.set(2,3,4);scene.add(key);const rim=new THREE.DirectionalLight(0xb6ecdf,2);rim.position.set(-3,2,-3);scene.add(rim);new ResizeObserver(resize).observe($('head-canvas'));resize();
 const pointers=new Map(),raycaster=new THREE.Raycaster();let moved=false;
 renderer.domElement.addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});moved=pointers.size>1;});renderer.domElement.addEventListener('pointermove',e=>{const start=pointers.get(e.pointerId);if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>7){moved=true;$('orientation').textContent='Vista livre';}});renderer.domElement.addEventListener('pointercancel',e=>pointers.delete(e.pointerId));renderer.domElement.addEventListener('pointerup',e=>{const start=pointers.get(e.pointerId);pointers.delete(e.pointerId);if(!start||moved||pointers.size||!activeModel)return;const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=raycaster.intersectObjects(groups.flatMap(g=>g.meshes).filter(m=>m.visible),false)[0];select(hit?.object.userData.record||null);});
 for(const button of document.querySelectorAll('[data-model]'))button.onclick=()=>choose(button.dataset.model);
 for(const[id,dir,label]of [['front',[0,0,1],'Vista de frente'],['back',[0,0,-1],'Vista de trás'],['right',[-1,0,0],'Lado direito'],['left',[1,0,0],'Lado esquerdo']])$(id).onclick=()=>{frame(wholeBox,new THREE.Vector3(...dir));$('orientation').textContent=label;};
 for(const[id,factor]of [['zoom-in',.8],['zoom-out',1.25]])$(id).onclick=()=>{const offset=camera.position.clone().sub(controls.target);offset.setLength(THREE.MathUtils.clamp(offset.length()*factor,controls.minDistance,controls.maxDistance));camera.position.copy(controls.target).add(offset);controls.update();draw();};
 $('restore').onclick=restore;$('search').oninput=renderList;
 $('hide').onclick=()=>{if(!selected)return;snapshot();const show=!selected.meshes.some(m=>m.visible);selected.meshes.forEach(m=>m.visible=show);select(selected);};
 $('isolate').onclick=()=>{if(!selected)return;snapshot();groups.forEach(g=>g.meshes.forEach(m=>m.visible=g===selected));frame(boundsOf([selected]));select(selected);};
 $('undo').onclick=()=>{const state=history.pop();if(!state)return;groups.forEach((g,i)=>g.meshes.forEach((m,j)=>m.visible=state[i][j]));$('undo').disabled=!history.length;select(selected);};
 setupDentalChart();choose('face');}
try{init();}catch(error){console.error(error);$('loading').textContent='O visualizador 3D não iniciou. Abra no Chrome com WebGL habilitado e tente atualizar a página.';}
