const names={
 'Pulmonary trunk':'Tronco pulmonar','Bifurcation of pulmonary trunk':'Bifurcação do tronco pulmonar','Left pulmonary artery':'Artéria pulmonar esquerda','Right pulmonary artery':'Artéria pulmonar direita',
 'Oesophagus':'Esôfago','Liver':'Fígado','Gallbladder':'Vesícula biliar','Stomach':'Estômago','Pancreas':'Pâncreas','Duodenum':'Duodeno','Jejunum':'Jejuno','Ascending colon':'Colo ascendente','Transverse colon':'Colo transverso','Descending colon':'Colo descendente','Sigmoid colon':'Colo sigmoide','Kidney':'Rim','Urinary bladder':'Bexiga urinária','Testis':'Testículo','Epididymis':'Epidídimo','Ductus deferens':'Ducto deferente','Ejaculatory duct':'Ducto ejaculatório','Seminal gland':'Glândula seminal','Prostate':'Próstata','Corpus cavernosum of penis':'Corpo cavernoso do pênis','Corpus spongiosum of penis':'Corpo esponjoso do pênis','Glans penis':'Glande do pênis','Adenohypophysis':'Adeno-hipófise','Neurohypophysis':'Neuro-hipófise','Pineal gland':'Glândula pineal','Thyroid gland':'Glândula tireoide','Inferior parathyroid gland':'Glândula paratireoide inferior','Superior parathyroid gland':'Glândula paratireoide superior','Suprarenal gland':'Glândula suprarrenal',
 'Atlas (C1)':'Atlas (C1)','Axis (C2)':'Áxis (C2)','Body of sternum':'Corpo do esterno','Calcaneus':'Calcâneo','Capitate bone':'Osso capitato','Clavicle':'Clavícula','Coccyx':'Cóccix','Cuboid bone':'Osso cuboide','Femur':'Fêmur','Fibula':'Fíbula','Hamate bone':'Osso hamato','Hip bone':'Osso do quadril','Humerus':'Úmero','Intermediate cuneiform bone':'Osso cuneiforme intermédio','Lateral cuneiform bone':'Osso cuneiforme lateral','Lunate bone':'Osso semilunar','Manubrium of sternum':'Manúbrio do esterno','Medial cuneiform bone':'Osso cuneiforme medial','Navicular bone':'Osso navicular','Patella':'Patela','Pisiform bone':'Osso pisiforme','Radius':'Rádio','Sacrum':'Sacro','Scaphoid bone':'Osso escafoide','Scapula':'Escápula','Sesamoid bones of foot':'Ossos sesamoides do pé','Talus':'Tálus','Tibia':'Tíbia','Trapezium bone':'Osso trapézio','Trapezoid bone':'Osso trapezoide','Triquetrum bone':'Osso piramidal','Ulna':'Ulna','Xiphoid process':'Processo xifoide'
};
const ordinals=['first','second','third','fourth','fifth','sixth','seventh','eighth','ninth','tenth','eleventh','twelfth'];
export function organName(source){
 const name=source.replace(/\.[lr]$/,'');if(names[name])return names[name];
 let m=name.match(/^Vertebra ([CTL]\d+)$/);if(m)return `Vértebra ${m[1]}`;
 m=name.match(/^(\w+) rib$/);if(m)return `${ordinals.indexOf(m[1].toLowerCase())+1}ª costela`;
 m=name.match(/^(\w+) (metacarpal|metatarsal) bone$/);if(m)return `${ordinals.indexOf(m[1].toLowerCase())+1}º ${m[2]==='metacarpal'?'metacarpal':'metatarsal'}`;
 m=name.match(/^(Distal|Middle|Proximal) phalanx of (\w+) finger of (foot|hand)$/);if(m)return `Falange ${{Distal:'distal',Middle:'média',Proximal:'proximal'}[m[1]]} do ${ordinals.indexOf(m[2])+1}º dedo ${m[3]==='foot'?'do pé':'da mão'}`;
 m=name.match(/^(.*?) artery of (left|right) lung$/);if(m){const parts={'Anterior basal segmental':'segmentar basal anterior','Anterior segmental':'segmentar anterior','Apical segmental':'segmentar apical','Inferior lingular':'lingular inferior','Inferior lobar':'lobar inferior','Lateral basal segmental':'segmentar basal lateral','Lateral segmental':'segmentar lateral','Medial basal segmental':'segmentar basal medial','Medial segmental':'segmentar medial','Middle lobar':'lobar média','Posterior basal segmental':'segmentar basal posterior','Posterior segmental':'segmentar posterior','Superior lingular':'lingular superior','Superior lobar':'lobar superior','Superior segmental':'segmentar superior'};if(parts[m[1]])return `Artéria ${parts[m[1]]} do pulmão ${m[2]==='left'?'esquerdo':'direito'}`;}
 return null;
}
